[[main]]
  identifier = "mindmaps"
  name = "mindmaps"
  url = "mindmaps"
  weight = 1

[[main]]
  identifier = "notes"
  name = "notes"
  url = "notes"
  weight = 2

[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 3