[[main]]
  identifier = "mindmaps"
  name = "mindmaps"
  url = "mindmaps"
  weight = 1

[[main]]
  identifier = "blogs"
  name = "blogs"
  url = "blogs"
  weight = 2

[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 3